### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by NanoBester** [Tao4free/QGIS_plugins#3]
Traceback (most recent call last):
			  File "/Users/arnobester/.qgis2/python/plugins/SuperLabeling/SuperLabelingDialog.py", line 156, in checkFieldInit
			    self.initField()
			  File "/Users/arnobester/.qgis2/python/plugins/SuperLabeling/SuperLabelingDialog.py", line 208, in initField
			    feature[share.field_list[0][0]] = feature[cbField_origin]
			KeyError: 'OBJ|Field'

**Comment by Tao4free** [comment]
I need more information about this error.
Could you send me the qgis project file and data to me? I will have a check.
You can send to my gmail: hakufu.asano@gmail.com
